#!/bin/sh

add_program() {
	echo .section .initrd.data
	echo .globl $1_beg, $1_end, $1_fsiz, $1_zsiz
	echo $1_beg:
	echo .incbin \"../$1/$1.bin\"
	echo .align 4096
	echo $1_end:
	echo .section .data
	echo $1_fsiz:
	echo .long `ls ../$1/$1.bin | awk '{print $5}'`
	echo $1_zsiz:
	echo .long `size ../$1/$1.sys | awk '{if (NR == 2) print $3}'`
}

echo "# initrd.S generated by $0"
prog() {
	add_program $1
}

prog sigma0
prog roottask
